### ISSUE TITLE
Unable to use on Windows

### ISSUE THREAD

**Issue by mslourens** [atao60/fse-cli#16]
### Description
When run on Windows I get the following error: ` UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

#### 🔬 Minimal Reproduction
Just run one of the fse commands on Windows via the scripts in package.json

#### 💻Your Environment

**Node Version:**

<pre><code>
14.16.0
</code></pre>

**fse-cli Version:**

<pre><code>
^0.1.6
</code></pre>

## 🔥 Exception or Error

<pre><code>

UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at Loader.import (internal/modules/esm/loader.js:165:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
</code></pre>

**Comment by atao60** [comment]
Thanks to report this issue.
Can you tell me more about:
- Windows version
- which commands and possible parameters

**Comment by atao60** [comment]
@mslourens can you check the new release 0.1.7. It should fix this issue.

**Comment by mslourens** [comment]
it works now. Thanks for your quick fix!
